### ISSUE TITLE
How do I configure VSCode to use uScope ?

### ISSUE THREAD

**Issue by linuxguy123** [DEMCON/uscope#1]
First off, thanks for developing uScope.   Good work !

Secondly, how does one configure VSCode to use uScope ?  With STLink ?  With JLink ?

Are you aware that the STLink driver (https://github.com/stlink-org/stlink) has a new driver called st-trace that allows SWO communication ?  st-util does not.    How would I set up uScope to use st-trace ?

Thanks

**Comment by TomSmeets** [comment]
Hello linuxguy123,

First, ensure that you have installed this extension correctly, either from the [marketplace](https://marketplace.visualstudio.com/items?itemName=DEMCON.uscope) or manually from GitHub following the instructions in the readme. This extension should be visible in the “Extensions” tab.

![image](https://github.com/DEMCON/uscope/assets/6740669/ada5d102-3bad-4057-9839-c2622d5fc23e)

Then the ‘uScope’ tab should be visible in the bottom panel. If there is no bottom panel it can be opened manually with the button in the top right corner.

![image](https://github.com/DEMCON/uscope/assets/6740669/e406ad00-69b7-46d8-8e78-efb0bef6f0ae)

Now you can connect to the J-Link or STLink driver on your laptop/PC.

For RTT start the ‘J-Link GDB Server’ on your laptop. Once it is running you can connect to it with uScope. Select RTT in the connection type and use the default host ‘127.0.0.1’ and default port ‘19021’ and then press connect. It should connect successfully and display log messages.

For SWO select ‘SWO’ in connection type, and ensure that the port matches the port displayed in the J-Link driver.

![image](https://github.com/DEMCON/uscope/assets/6740669/6cf47db3-6566-4bbb-9cb7-47a98d9ac4ed)

This works similarly with the official ST-Link drivers from st.com. However the port might be different.

About the Open Source "stlink" driver, I was aware of project, but I personally used the official drives from st.com. The open source driver does not seem to advertise a socket for SWO, and only output it to the console. It should not be too difficult to modify this tool to also send SWO text over a local socket. But for now, one possibility (in linux) is to pipe the st-trace output to gnu-netcat. And then connect to the port '61235' with uScope. Something like this: (I did not test this yet)

```bash
st-trace | nc -l -p 61235
```

Let me know if this works for you. :)
